USE [master]
GO

/****** Object:  Database [BD_Entrevistas]    Script Date: 12/03/2020 2:56:35 p. m. ******/
CREATE DATABASE [BD_Entrevistas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Entrevistas', FILENAME = N'D:\DataSql\Entrevistas.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Entrevistas_log', FILENAME = N'D:\DataSql\Entrevistas_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BD_Entrevistas] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Entrevistas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_Entrevistas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Entrevistas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Entrevistas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_Entrevistas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_Entrevistas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_Entrevistas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BD_Entrevistas] SET  MULTI_USER 
GO

ALTER DATABASE [BD_Entrevistas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_Entrevistas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_Entrevistas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_Entrevistas] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BD_Entrevistas] SET  READ_WRITE 
GO


