//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrevistasApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrevistas
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public string NombresCompletos { get; set; }
        public string ModalidadEntrevista { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
    }
}
